[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Oliver Ni <oliver.ni@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
